name: Escuela Ameyalli
favicon: null
layout_spectrum: 0.75726
typography_spectrum: 0.27224
title: Escuela Ameyalli
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171612'
    - '#4c4b47'
    - '#858179'
    - '#a3c9eb'
    - '#9c1417'
  brandStrength: 0.375
  lightness: 0.9664054396562278
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
