name: Escuela Ameyalli
favicon: null
layout_spectrum: 0.89146
typography_spectrum: 0.36797
title: Escuela Ameyalli
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.75
  lightness: 0.9664054396562278
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
